// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tcsqkladukfzielusirl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRjc3FrbGFkdWtmemllbHVzaXJsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0NDM1MjcsImV4cCI6MjA2MTAxOTUyN30.L6FvnHHSHo3ebg6YEKHNqaIaOPVptjVoPj2e0KgyA8k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);